### ISSUE TITLE
Library not working in oreo

### ISSUE THREAD

**Issue by anikraj1994** [youtube/api-samples#155]
The youtube library fails to load in Oreo.
ERROR_CONNECTING_TO_SERVICE

**Comment by khaleeljageer** [comment]
Facing the same issue.

**Comment by vivekm26** [comment]
Facing the same issue.

**Comment by Tanachha** [comment]
why?

**Comment by vivekm26** [comment]
When the youtube app is not playing in the background and when we try to initialize the youtube api in our application, then we face this issue. However,  when the youtube app is running in the background it is working as expected. It is working as expected for Android OS <= Android N

**Comment by deeps2HOG** [comment]
I am also facing similar issue on One Plus 5T running oreo. I am using YouTube fragment to play the videos as suggested in their doc.

Once I get ERROR_CONNECTING_TO_SERVICE error and then I press back to close the activity, I get another error. The error persists even after killing the app:
 ```
E/ActivityThread: Activity com.tf.eros.faythTv.activity.YouTubeVideoActivity has leaked ServiceConnection com.google.android.youtube.player.internal.r$e@6555dd3 that was originally bound here
                                                         android.app.ServiceConnectionLeaked: Activity com.tf.eros.faythTv.activity.YouTubeVideoActivity has leaked ServiceConnection com.google.android.youtube.player.internal.r$e@6555dd3 that was originally bound here
                                                             at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1565)
                                                             at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1457)
                                                             at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1606)
                                                             at android.app.ContextImpl.bindService(ContextImpl.java:1558)
                                                             at android.content.ContextWrapper.bindService(ContextWrapper.java:679)
                                                             at com.google.android.youtube.player.internal.r.e(Unknown Source:74)
                                                             at com.google.android.youtube.player.YouTubePlayerView.a(Unknown Source:70)
                                                             at com.google.android.youtube.player.YouTubePlayerFragment.a(Unknown Source:29)
                                                             at com.google.android.youtube.player.YouTubePlayerFragment.initialize(Unknown Source:11)
                                                             at com.tf.eros.faythTv.activity.YouTubeVideoActivity.onCreate(YouTubeVideoActivity.java:108)
                                                             at android.app.Activity.performCreate(Activity.java:6998)
                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1230)
                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
                                                             at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
                                                             at android.os.Handler.dispatchMessage(Handler.java:105)
                                                             at android.os.Looper.loop(Looper.java:164)
                                                             at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by deeps2HOG** [comment]
Well, I couldn't find a concrete solution for this...But there is a way around. Once the init fail, you can open YouTubeStandalonePlayer inside onInitFailure(). For that:
 ```
@Override
    public void onInitializationFailure(YouTubePlayer.Provider provider, YouTubeInitializationResult youTubeInitializationResult) {
        try {
            Intent intent = YouTubeStandalonePlayer.createVideoIntent(this, <API_KEY>, <videoID>);
            startActivity(intent);
            finish(); //to exit current Activity
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

**Comment by ChrisWbe** [comment]
Thanks deepsHOG, i could not find a solution.

**Comment by sjmach** [comment]
I am also getting the same issue.

**Comment by r9software** [comment]
Having same issue with YouTubePlayerView

**Comment by wider2** [comment]
I confirm
This library works perfect on previous Android versions
but nowadays we are using Oreo.... and library becomes outdated

**Comment by samimw** [comment]
I am having same issue, did anyone solve this?

**Comment by sagarsurani** [comment]
I am having the same issue with our app.

**Comment by kkayri** [comment]
C'est trop compliqué pour moi à cause des d'étapes
