### ISSUE TITLE
Getting Crash on Android Latest versions

### ISSUE THREAD

**Issue by aashu09** [youtube/api-samples#193]
Hi Support, 
Please look below issue, its causing me the app crashing on my play store build. Please review it fast, its necessary for me.

Android Version on which error occuring - 8.0

05-10 18:35:45.194 13222-13222/? E/ActivityThread: Service com.google.android.youtube.api.service.YouTubeService has leaked IntentReceiver acsi@53953a1 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Service com.google.android.youtube.api.service.YouTubeService has leaked IntentReceiver acsi@53953a1 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1351)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1132)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1421)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1394)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1382)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:609)
        at aeel.<init>(SourceFile:65)
        at aefc.get(SourceFile:46)
        at anzy.get(SourceFile:10)
        at kwk.r(SourceFile:263)
        at acra.get(SourceFile:11)
        at anzy.get(SourceFile:10)
        at kwm.a(SourceFile:10)
        at kuw.<init>(SourceFile:21)
        at com.google.android.apps.youtube.embeddedplayer.service.service.jar.ApiPlayerService.<init>(SourceFile:52)
        at com.google.android.apps.youtube.embeddedplayer.service.service.jar.ApiPlayerFactoryService$1.run(SourceFile:10)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-10 18:35:45.208 13222-13222/? E/ActivityThread: Service com.google.android.youtube.api.service.YouTubeService has leaked IntentReceiver acsl@fcd8e1c that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Service com.google.android.youtube.api.service.YouTubeService has leaked IntentReceiver acsl@fcd8e1c that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1351)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1132)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1421)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1394)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1382)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:609)
        at acsj.<init>(SourceFile:17)
        at acsq.get(SourceFile:16)
        at aefc.get(SourceFile:36)
        at anzy.get(SourceFile:10)
        at kwk.r(SourceFile:263)
        at acra.get(SourceFile:11)
        at anzy.get(SourceFile:10)
        at kwm.a(SourceFile:10)
        at kuw.<init>(SourceFile:21)
        at com.google.android.apps.youtube.embeddedplayer.service.service.jar.ApiPlayerService.<init>(SourceFile:52)
        at com.google.android.apps.youtube.embeddedplayer.service.service.jar.ApiPlayerFactoryService$1.run(SourceFile:10)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by aashu09** [comment]
Anybody is there for responses or solving an issue?

**Comment by PrashantpEdcast** [comment]
I got the same issue any update on this?

**Comment by Lucaslah** [comment]
Is the android versions beta.
If beta get rid of beta beta's can sometimes have lots of bugs
Hope this will help
Thanks
