### ISSUE TITLE
Error from YouTube Analytics API Call

### ISSUE THREAD

**Issue by STANAPI** [youtube/api-samples#213]
Hi, I have encountered the below issue. Could anyone advise on this? Thank you very much.

The YouTube Analytics API Call encountered the following exception: 
Traceback (most recent call last):
  File "C:\STB\STAN_MG_API\YouTube\yt_channel_insights_video_retention.py", line 201, in <module>
    (youtube, youtube_analytics) = get_authenticated_services(args)
  File "C:\STB\STAN_MG_API\YouTube\yt_channel_insights_video_retention.py", line 118, in get_authenticated_services
    http=http)
  File "C:\Python27\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Python27\lib\site-packages\googleapiclient\discovery.py", line 228, in build
    requested_url, discovery_http, cache_discovery, cache)
  File "C:\Python27\lib\site-packages\googleapiclient\discovery.py", line 275, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "C:\Python27\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Python27\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Python27\lib\site-packages\httplib2\__init__.py", line 1659, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Python27\lib\site-packages\httplib2\__init__.py", line 1399, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Python27\lib\site-packages\httplib2\__init__.py", line 1355, in _conn_request
    response = conn.getresponse()
  File "C:\Python27\lib\httplib.py", line 1121, in getresponse
    response.begin()
  File "C:\Python27\lib\httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "C:\Python27\lib\httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "C:\Python27\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "C:\Python27\lib\ssl.py", line 766, in recv
    return self.read(buflen)
  File "C:\Python27\lib\ssl.py", line 653, in read
    v = self._sslobj.read(len)
error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by hassan17hassan18** [comment]
Fm

**Comment by hassan17hassan18** [comment]
Hassanalasmari

**Comment by hassan17hassan18** [comment]
Fm
