### ISSUE TITLE
batch_report_download.py doesn't work anymore.

### ISSUE THREAD

**Issue by lenguyenthedat** [youtube/api-samples#26]
Here is the error log:

    $ python batch_report_download.py  --content-owner-id [my-content-owner-id] --report-type claims
    Your browser has been opened to visit:

        https://accounts.google.com/o/oauth2/auth?scope=...

    If your browser is on a different machine then exit and re-run this
    application with the command-line parameter 

      --noauth_local_webserver

    Authentication successful.
    Traceback (most recent call last):
      File "batch_report_download.py", line 117, in <module>
        reports = get_available_reports(youtubeAnalytics, args.content_owner_id)
      File "batch_report_download.py", line 81, in get_available_reports
        return definitions_list_response["items"]
    KeyError: 'items'

Mostly because `youtubeAnalytics.batchReportDefinitions.list`'s result is empty, see result from https://developers.google.com/apis-explorer/#s/youtubeAnalytics/v1beta1/youtubeAnalytics.batchReportDefinitions.list

![screen shot 2015-05-12 at 13 02 45](https://cloud.githubusercontent.com/assets/1543321/7580402/4b341d3c-f8a7-11e4-8918-3ad8ea24391b.png)

Am I missing something here or Is there any way to fix this? I've tried to google around a lot and still can not find any solution to this.

**Comment by pprmint** [comment]
@lenguyenthedat  I'm also having the same issue, did you find any solution to this?

**Comment by lenguyenthedat** [comment]
Nope, we had to use https://developers.google.com/apis-explorer/#s/youtubeAnalytics/v1beta1/youtubeAnalytics.reports.query instead.

**Comment by pprmint** [comment]
@lenguyenthedat Have you tried contacting any developers from youtube?
I really need the reports downloading feature. Have made it work before?

**Comment by lenguyenthedat** [comment]
@pprmint nope, I only did it via this github issue.
AFAIK it doesn't work 6 months ago, not sure about before that since I didn't touch them then.

Hope this help: https://github.com/lenguyenthedat/google-data-api-tutorials/tree/master/Youtube

**Comment by pprmint** [comment]
@lenguyenthedat thanks! Anyway, I have means to contact them and I've already done so. 
If they have any reply, Ill post it here.

**Comment by pprmint** [comment]
@lenguyenthedat I got a reply from youtube and they explained that the API is not yet available or out in production. But they enabled it on our account at least that's what I understood.

**Comment by iulukaya** [comment]
Yes, there will be a new API in testing stage for batch reporting. I think that's why this old one stopped working.

**Comment by kokphinsheng** [comment]
Schism between you and tomorrow night for me
