### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by YashuC** [youtube/api-samples#309]
So I am doing a auto matic tittle updater for my youtube video and when i try to run my server.js/quickstart.js I getting some errors like this:

 var redirectUrl = credentials.installed.redirect_uris[0];
                                                                               ^

TypeError: Cannot read property '0' of undefined
    at authorize (E:\Desktop\YoutubeVideoUpdater\server.js:31:56)
    at processClientSecrets (E:\Desktop\YoutubeVideoUpdater\server.js:18:3)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

The Code is given below:
[server.zip](https://github.com/youtube/api-samples/files/5480730/server.zip)

Also i am using the same client_secret.jason file that i downloaded no change.

**Comment by illegitimate-egg** [comment]
You file was flagged as malware

**Comment by illegitimate-egg** [comment]
I have the same problem though, if I find a solution I will try to help you
