### ISSUE TITLE
OSError: [Errno 98] Address already in use...while uploading video....Django , Apache, Youtube API 3;  

### ISSUE THREAD

**Issue by harshjadon9** [youtube/api-samples#328]
###  i m trying to upload a video from my server to youtube through django.

**django, 
youtube API 3, 
apache server ( VPS )**

**error:**
`OSError: [Errno 98] Address already in use`

**error on line:**
`cred = flow.run_local_server(port=8080)`

**complete error**
```
Internal Server Error: /pixiv/create/.  #my link
Traceback (most recent call last):
  File "/django/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/django/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/django/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/django/mp3/main/views.py", line 370, in ytpixiv
    service = Create_Service(CLIENT_SECRET_FILE, API_NAME, API_VERSION, SCOPES)
  File "/django/mp3/main/Google.py", line 31, in Create_Service
    **cred = flow.run_local_server(port=8080)**
  File "/django/venv/lib/python3.6/site-packages/google_auth_oauthlib/flow.py", line 458, in run_local_server
    host, port, wsgi_app, handler_class=_WSGIRequestHandler
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 153, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
    **self.socket.bind(self.server_address)
  OSError: [Errno 98] Address already in use**
```

**Comment by firozzer** [comment]
Hi, did you find any fix for this? Thanks.
