### ISSUE TITLE
error when running python sample

### ISSUE THREAD

**Issue by stephane-archer** [youtube/api-samples#547]
```
python3 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 41, in <module>
    service = get_authenticated_service()
  File "quickstart.py", line 24, in get_authenticated_service
    credentials = flow.run_console()
AttributeError: 'InstalledAppFlow' object has no attribute 'run_console'
```

**Comment by vaylvn** [comment]
Seconded, simply using the example code provided via the api site and getting the same issue.
