### ISSUE TITLE
playlist_updates.py is broken in newer versions of python

### ISSUE THREAD

**Issue by ilmn-pmansfield** [youtube/api-samples#550]
```
./playlist_updates.py
  File "/home/pmansfield/git/pmansfield/devops_utilities/google/./playlist_updates.py", line 60
    print 'New playlist ID: %s' % playlists_insert_response['id']
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

then

```
$ ./playlist_updates.py
  File "/home/pmansfield/git/pmansfield/devops_utilities/google/./playlist_updates.py", line 77
    except HttpError, e:
           ^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
```

then
```
$ ./playlist_updates.py
  File "/home/pmansfield/git/pmansfield/devops_utilities/google/./playlist_updates.py", line 78
    print 'An HTTP error %d occurred:\n%s' % (e.resp.status, e.content)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

then
```$ ./playlist_updates.py
Traceback (most recent call last):
  File "/home/pmansfield/git/pmansfield/devops_utilities/google/./playlist_updates.py", line 74, in <module>
    youtube = get_authenticated_service()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pmansfield/git/pmansfield/devops_utilities/google/./playlist_updates.py", line 40, in get_authenticated_service
    credentials = flow.run_console()
                  ^^^^^^^^^^^^^^^^
AttributeError: 'InstalledAppFlow' object has no attribute 'run_console'
```

**Comment by ilmn-pmansfield** [comment]
most of the google examples seem woefully out of date or totally broken. dismal effort, google, shameful!
